language: c
sudo: false
before_install:
  - mkdir opt
  - git clone https://github.com/raspberrypi/tools ./
  - mv ./tools/arm-bcm2708 ./opt/
  - export PATH=$PATH:./opt/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin
before_script:
  - git clone -b rpi-4.9.y --depth=1 https://github.com/raspberrypi/linux ./opt/source/rpi-4.9/smp
  - cd ./opt/source/rpi-4.9/smp
  - make mrproper
script:


