language: c
sudo: required
cache:
  ccache: true
  directories:
    - $HOME/downloads
before_install:
  - mkdir opt
  - git clone https://github.com/raspberrypi/tools ./
  - mv ./tools/arm-bcm2708 ./opt/
  - export PATH=$PATH:./opt/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin
before_script:
  - git clone -b rpi-4.9.y --depth=1 https://github.com/raspberrypi/linux ./opt/source/rpi-4.9/smp
  - cd ./opt/source/rpi-4.9/smp
  - make mrproper
script:
  - make -j3 ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- bcm2709_defconfig
  - make -j3 ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- zImage modules dtbs
  - mkdir -p ../../../../opt/install/rpi-4.9
  - sudo make -j3 ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- modules_install INSTALL_MOD_PATH=../../../../opt/install/rpi-4.9
  - sudo scripts/mkknlimg arch/arm/boot/zImage ../../../../opt/install/rpi-4.9/kernel7.img
after_script:
  - mkdir ../../../../upload
  - mkdir ../../../../upload/file
  - tar czvf ../../../../upload/file/dts.tgz arch/arm/boot/dts
  - tar czvf ../../../../upload/file/modules.tgz ../../../../opt/install/rpi-4.9/modules
  - cd ../../../../upload
  - git init
  - git config user.name "xjx00"
  - git config user.email "xjxyklwx@126.com"
  - git add .
  - git commit -m "Update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:upload
