sudo: required
services:
  - docker
language: bash
script:
  - chmod +x travis-build.sh
  - ./travis-build.sh
after_success:
  - ls -al builds/$BUILD_NR/*
branches:
  only:
    - master
  except:
    - /^v\d.*$/
